"""empty message

Revision ID: efcfecd488f2
Revises: b3e5de774c2f
Create Date: 2024-02-16 14:43:01.734311

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'efcfecd488f2'
down_revision = 'b3e5de774c2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Enum('Confirmee', 'annulee', 'En cours de validation', name='status_of_booking'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('Confirmee', 'annulee', 'En cours de validation', name='status_of_booking'),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
